class Post {
  int? id; // auto-generated by SQLite
  String title;
  String body;

  Post({this.id, required this.title, required this.body});

  // Convert Post object → Map (to save into SQLite)
  Map<String, dynamic> toMap() {
    return {'id': id, 'title': title, 'body': body};
  }

  // Convert Map (from SQLite) → Post object
  factory Post.fromMap(Map<String, dynamic> map) {
    return Post(id: map['id'], title: map['title'], body: map['body']);
  }
}
